### ISSUE TITLE
MiscFileInfo is not found in the database

### ISSUE THREAD

**Issue by tristpinsm** [chime-experiment/chimedb_di#10]
After pulling the latest `master`, my pipeline calls to `ch_pipeline.io.QueryDatabase` fail with:

```
    24.5s [MPI  0/16] - DEBUG    peewee: ('SELECT Min(`t1`.`start_time`) FROM `archivefile` AS `t2` INNER JOIN `rawadcfileinfo` AS `t1` ON (`t1`.`file_id` = `t2`.`id`) WHERE (`t2`.`acq_id` = %s)', [4026])
    24.5s [MPI  0/16] - DEBUG    peewee: ('SELECT Min(`t1`.`start_time`) FROM `archivefile` AS `t2` INNER JOIN `hkpfileinfo` AS `t1` ON (`t1`.`file_id` = `t2`.`id`) WHERE (`t2`.`acq_id` = %s)', [4026])
    24.5s [MPI  0/16] - DEBUG    peewee: ('SELECT Min(`t1`.`start_time`) FROM `archivefile` AS `t2` INNER JOIN `digitalgainfileinfo` AS `t1` ON (`t1`.`file_id` = `t2`.`id`) WHERE (`t2`.`acq_id` = %s)', [4026])
    24.5s [MPI  0/16] - DEBUG    peewee: ('SELECT Min(`t1`.`start_time`) FROM `archivefile` AS `t2` INNER JOIN `calibrationgainfileinfo` AS `t1` ON (`t1`.`file_id` = `t2`.`id`) WHERE (`t2`.`acq_id` = %s)', [4026])
    24.5s [MPI  0/16] - DEBUG    peewee: ('SELECT Min(`t1`.`start_time`) FROM `archivefile` AS `t2` INNER JOIN `flaginputfileinfo` AS `t1` ON (`t1`.`file_id` = `t2`.`id`) WHERE (`t2`.`acq_id` = %s)', [4026])
    24.5s [MPI  0/16] - DEBUG    peewee: ('SELECT Min(`t1`.`start_time`) FROM `archivefile` AS `t2` INNER JOIN `miscfileinfo` AS `t1` ON (`t1`.`file_id` = `t2`.`id`) WHERE (`t2`.`acq_id` = %s)', [4026])
Traceback (most recent call last):
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'ch_data.miscfileinfo' doesn't exist")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/tristpm/beam_processing/holo_fstop/rev_00/code/caput/caput/scripts/runner.py", line 300, in <module>
    cli()
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/scratch/tristpm/beam_processing/holo_fstop/rev_00/code/caput/caput/scripts/runner.py", line 51, in run
    P.run()
  File "/scratch/tristpm/beam_processing/holo_fstop/rev_00/code/caput/caput/pipeline.py", line 547, in run
    out = task._pipeline_next()
  File "/scratch/tristpm/beam_processing/holo_fstop/rev_00/code/caput/caput/pipeline.py", line 892, in _pipeline_next
    out = self.setup(*tuple(self._requires))
  File "/scratch/tristpm/beam_processing/holo_fstop/rev_00/code/ch-pipeline/ch_pipeline/core/dataquery.py", line 281, in setup
    results = f.get_results()
  File "/scratch/tristpm/beam_processing/holo_fstop/rev_00/code/ch-util/ch_util/finder.py", line 1344, in get_results
    intervals += self.get_results_acq(ii, file_condition)
  File "/scratch/tristpm/beam_processing/holo_fstop/rev_00/code/ch-util/ch_util/finder.py", line 1214, in get_results_acq
    acq_start = acq.start_time
  File "/scratch/tristpm/beam_processing/holo_fstop/rev_00/code/chimedb.di/chimedb/data_index/orm.py", line 160, in start_time
    self.files.select(pw.fn.Min(model.start_time)).join(model).scalar()
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 1812, in inner
    return method(self, database, *args, **kwargs)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 2073, in scalar
    row = self.tuples().peek(database)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 1812, in inner
    return method(self, database, *args, **kwargs)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 2060, in peek
    rows = self.execute(database)[:n]
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 1812, in inner
    return method(self, database, *args, **kwargs)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 1883, in execute
    return self._execute(database)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 2054, in _execute
    cursor = database.execute(self)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 3018, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/scratch/tristpm/beam_processing/holo_fstop/rev_00/code/chimedb/chimedb/core/connectdb.py", line 253, in execute_sql
    cursor = super(RetryOperationalError, self).execute_sql(sql, params, commit)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 3012, in execute_sql
    self.commit()
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 2783, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
peewee.ProgrammingError: (1146, "Table 'ch_data.miscfileinfo' doesn't exist")
```

**Comment by tristpinsm** [comment]
@ketiltrout Any idea why this is happening? I've just been rolling back the latest commit to run my pipeline.

**Comment by tristpinsm** [comment]
I guess we need to add the `miscfileinfo` table to the database

**Comment by ketiltrout** [comment]
Okay, looks good now:
```
MariaDB [ch_data]> describe miscfileinfo;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| file_id     | int(11)      | NO   | MUL | NULL    |                |
| start_time  | double       | YES  |     | NULL    |                |
| finish_time | double       | YES  |     | NULL    |                |
| data_type   | varchar(255) | NO   |     | NULL    |                |
| metadata    | longtext     | NO   |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)

MariaDB [ch_data]> show create table miscfileinfo\G
*************************** 1. row ***************************
       Table: miscfileinfo
Create Table: CREATE TABLE `miscfileinfo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `file_id` int(11) NOT NULL,
  `start_time` double DEFAULT NULL,
  `finish_time` double DEFAULT NULL,
  `data_type` varchar(255) NOT NULL,
  `metadata` longtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `miscfileinfo_file_id` (`file_id`),
  CONSTRAINT `miscfileinfo_ibfk_1` FOREIGN KEY (`file_id`) REFERENCES `archivefile` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

MariaDB [ch_data]> show keys from miscfileinfo;
+--------------+------------+----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table        | Non_unique | Key_name             | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+--------------+------------+----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| miscfileinfo |          0 | PRIMARY              |            1 | id          | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
| miscfileinfo |          1 | miscfileinfo_file_id |            1 | file_id     | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
+--------------+------------+----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
2 rows in set (0.00 sec)
```
